-- "addons\\darkrpmodification\\lua\\darkrp_customthings\\doorgroups.lua"
-- Retrieved by https://github.com/lewisclark/glua-steal
--[[---------------------------------------------------------------------------
Door groups
---------------------------------------------------------------------------
The server owner can set certain doors as owned by a group of people, identified by their jobs.


HOW TO MAKE A DOOR GROUP:
AddDoorGroup("NAME OF THE GROUP HERE, you will see this when looking at a door", Team1, Team2, team3, team4, etc.)
---------------------------------------------------------------------------]]


-- Example: AddDoorGroup("Cops and Mayor only", TEAM_CHIEF, TEAM_POLICE, TEAM_MAYOR)
-- Example: AddDoorGroup("Gundealer only", TEAM_GUN)
AddDoorGroup("Альянс", TEAM_CONSUL, TEAM_HAZWORKER, TEAM_WORKER_UNIT, TEAM_MPF_JURY_Conscript, TEAM_CMDCURATOR, TEAM_MPF_JURY_PVT, TEAM_MPF_JURY_CPL, TEAM_MPF_JURY_SGT, TEAM_MPF_JURY_LT, TEAM_MPF_ETHERNAL_SGT, TEAM_MPF_ETHERNAL_LT, TEAM_MPF_ETHERNAL_CPT, TEAM_MPF_PLUNGER_SGT, TEAM_MPF_PLUNGER_LT, TEAM_MPF_PLUNGER_CPT, TEAM_MPF_WATCHER_SGT, TEAM_MPF_WATCHER_LT, TEAM_MPF_WATCHER_CPT, TEAM_MPF_SPIRE_SGT, TEAM_MPF_SPIRE_LT, TEAM_MPF_SPIRE_CPT, TEAM_MPF_JURY_CPT, TEAM_MPF_JURY_GEN, TEAM_OWUDISPATCH, TEAM_OTA_Grunt, TEAM_OTA_Suppressor, TEAM_OTA_Hammer, TEAM_OTA_Ordinal, TEAM_OTA_Soldier, TEAM_OTA_Striker, TEAM_OTA_Razor, TEAM_OTA_Assassin, TEAM_OTA_Tech, TEAM_OTA_Commander, TEAM_OTA_Elite, TEAM_OTA_Crypt, TEAM_OTA_Broken, TEAM_REBELSPY01, TEAM_PARTYGENERALSECRETARY)
AddDoorGroup("Повстанцы", TEAM_REBELNEWBIE, TEAM_REBELSOLDAT, TEAM_REBELMEDIC, TEAM_REBELENGINEER, TEAM_REBELSPY02, TEAM_REBELSPY01, TEAM_REBEL_VETERAN, TEAM_REBEL_COMMANDER, TEAM_REBELLEADER, TEAM_REBELJUGGER, TEAM_LAMBDASOLDAT, TEAM_LAMBDASNIPER, TEAM_LAMBDACOMMANDER)
AddDoorGroup("ГСР", TEAM_CONSUL, TEAM_CUWRUBBISH, TEAM_CUWFOODCOURIER, TEAM_CUWFOODCOOK, TEAM_CUWFOODCOMPILER, TEAM_CUWFOODNATUR, TEAM_CUWMINMINER, TEAM_DOCTOR, TEAM_PARTYCANDIDATE, TEAM_PARTYMEMBER, TEAM_PARTYSUPPORT, TEAM_PARTYSUPPORTSUPERIOR, TEAM_PARTYWORKSUPERVISOR, TEAM_PARTYSUPERIORCOUNCILMEMBER, TEAM_PARTYCOUNCILCHAIRMAN, TEAM_PARTYGENERALSECRETARY, TEAM_MPF_JURY_Conscript, TEAM_CMDCURATOR, TEAM_MPF_JURY_PVT, TEAM_MPF_JURY_CPL, TEAM_MPF_JURY_SGT, TEAM_MPF_JURY_LT, TEAM_MPF_ETHERNAL_SGT, TEAM_MPF_ETHERNAL_LT, TEAM_MPF_ETHERNAL_CPT, TEAM_MPF_PLUNGER_SGT, TEAM_MPF_PLUNGER_LT, TEAM_MPF_PLUNGER_CPT, TEAM_MPF_WATCHER_SGT, TEAM_MPF_WATCHER_LT, TEAM_MPF_WATCHER_CPT, TEAM_MPF_SPIRE_SGT, TEAM_MPF_SPIRE_LT, TEAM_MPF_SPIRE_CPT, TEAM_MPF_JURY_CPT, TEAM_MPF_JURY_GEN, TEAM_OWUDISPATCH, TEAM_OTA_Grunt, TEAM_OTA_Suppressor, TEAM_OTA_Hammer, TEAM_OTA_Ordinal, TEAM_REBELSPY01, TEAM_PARTYGENERALSECRETARY, TEAM_REBELSPY02, TEAM_REBELSPY01)
AddDoorGroup("Верховная Партия Альянса", TEAM_CONSUL, TEAM_PARTYCANDIDATE, TEAM_PARTYMEMBER, TEAM_PARTYSUPPORT, TEAM_PARTYSUPPORTSUPERIOR, TEAM_PARTYWORKSUPERVISOR, TEAM_PARTYSUPERIORCOUNCILMEMBER, TEAM_PARTYCOUNCILCHAIRMAN, TEAM_PARTYGENERALSECRETARY, TEAM_MPF_JURY_Conscript, TEAM_CMDCURATOR, TEAM_MPF_JURY_PVT, TEAM_MPF_JURY_CPL, TEAM_MPF_JURY_SGT, TEAM_MPF_JURY_LT, TEAM_MPF_ETHERNAL_SGT, TEAM_MPF_ETHERNAL_LT, TEAM_MPF_ETHERNAL_CPT, TEAM_MPF_PLUNGER_SGT, TEAM_MPF_PLUNGER_LT, TEAM_MPF_PLUNGER_CPT, TEAM_MPF_WATCHER_SGT, TEAM_MPF_WATCHER_LT, TEAM_MPF_WATCHER_CPT, TEAM_MPF_SPIRE_SGT, TEAM_MPF_SPIRE_LT, TEAM_MPF_SPIRE_CPT, TEAM_MPF_JURY_CPT, TEAM_MPF_JURY_GEN, TEAM_OWUDISPATCH, TEAM_OTA_Grunt, TEAM_OTA_Suppressor, TEAM_OTA_Hammer, TEAM_OTA_Ordinal, TEAM_REBELSPY01, TEAM_PARTYGENERALSECRETARY, TEAM_REBELSPY02, TEAM_REBELSPY01)
