-- "addons\\do_on_death\\lua\\autorun\\client\\language.lua"
-- Retrieved by https://github.com/lewisclark/glua-steal
--
-- Death Sounds
--

-- English
language.Add("dod.en.settings", "Settings")
language.Add("dod.en.death_sounds_settings", "Sounds settings")
language.Add("dod.en.weapon_settings", "Weapons settings")
language.Add("dod.en.admin_restricted", "You don't have the admin rights to edit those settings.")
language.Add("dod.en.enable_death_sounds", "Enable death sounds")
language.Add("dod.en.enable_beep_sounds", "Enable the beep-beeep-beeeep death sound")
language.Add("dod.en.character_gender", "Character gender:")
language.Add("dod.en.character_gender.male", "Man")
language.Add("dod.en.character_gender.female", "Woman")
language.Add("dod.en.character_gender.zombie", "Zombie")
language.Add("dod.en.character_gender.autodetection", "Auto-detection")
language.Add("dod.en.enable_drop_weapons", "Enable weapon dropping on death")
language.Add("dod.en.allow_pickup_dropped_weapons", "Allow players to pickup dropped weapons")
language.Add("dod.en.drop_weapons_mode", "Drop mode:")
language.Add("dod.en.drop_weapons_mode.drop_all", "Drop all weapons on the ground")
language.Add("dod.en.drop_weapons_mode.drop_current", "Drop the active weapon only")
language.Add("dod.en.max_dropped_weapons", "Max dropped weapons:")
language.Add("dod.en.weapon_stay_limit", "Weapon stay limit:")
language.Add("dod.en.pickup_mode", "Pickup mode:")
language.Add("dod.en.pickup_mode.use", "By pressing the USE key")
language.Add("dod.en.pickup_mode.walk", "By walking on weapons")
language.Add("dod.en.weapon_halo_enable", "Display a halo on dropped weapons")
language.Add("dod.en.other_settings", "Other settings")
language.Add("dod.en.red_screen_of_death_enable", "Enable the red screen of death")

-- French
language.Add("dod.fr.settings", "Paramètres")
language.Add("dod.fr.death_sounds_setting", "Paramètres des sons")
language.Add("dod.fr.weapon_setting", "Paramètres des armes")
language.Add("dod.fr.admin_restricted", "Vous n'avez pas les droits d'admin pour modifier ces paramètres.")
language.Add("dod.fr.enable_death_sounds", "Activer les bruitages lors de la mort")
language.Add("dod.fr.enable_beep_sounds", "Activer le bip-biip-biiip lors de la mort")
language.Add("dod.fr.character_gender", "Genre du joueur :")
language.Add("dod.fr.character_gender.male", "Homme")
language.Add("dod.fr.character_gender.female", "Femme")
language.Add("dod.fr.character_gender.zombie", "Zombie")
language.Add("dod.fr.character_gender.autodetection", "Détection auto")
language.Add("dod.fr.enable_drop_weapons", "Activer la perte des armes lors de la mort")
language.Add("dod.fr.allow_pickup_dropped_weapons", "Autoriser la récupération des armes perdues")
language.Add("dod.fr.drop_weapons_mode", "Perte des armes :")
language.Add("dod.fr.drop_weapons_mode.drop_all", "Jeter les armes au sol")
language.Add("dod.fr.drop_weapons_mode.drop_current", "Jeter l'arme active uniquement")
language.Add("dod.fr.max_dropped_weapons", "Max. armes lâchées :")
language.Add("dod.fr.weapon_stay_limit", "Persistance au sol :")
language.Add("dod.fr.pickup_mode", "Récup. des armes :")
language.Add("dod.fr.pickup_mode.use", "En utilisant la touche UTILISER")
language.Add("dod.fr.pickup_mode.walk", "En marchant sur les armes")
language.Add("dod.fr.weapon_halo_enable", "Afficher un halo sur les armes au sol")
language.Add("dod.fr.other_settings", "Paramètres divers")
language.Add("dod.fr.red_screen_of_death_enable", "Active le filtre rouge à la mort")
