-- "addons\\rised_config\\lua\\autorun\\rc_trade_npc.lua"
-- Retrieved by https://github.com/lewisclark/glua-steal
if RISED == null then
	RISED = {}
	if RISED.Config == null then
		RISED.Config = {}
	end
end

----------========== Торговцы ==========----------
RISED.Config.Trade = {}
RISED.Config.Trade.TradeNPC = {}

RISED.Config.Trade.ItemsRarity = {}
RISED.Config.Trade.ItemsRarity.COMMON = 90
RISED.Config.Trade.ItemsRarity.UNCOMMON = 60
RISED.Config.Trade.ItemsRarity.RARE = 25
RISED.Config.Trade.ItemsRarity.LEGENDARY = 5

RISED.Config.Trade.Doctor = {}
RISED.Config.Trade.Doctor.Refrash = 1200
RISED.Config.Trade.Doctor.IsRandomRotation = false
RISED.Config.Trade.Doctor.MaxItems = 13
RISED.Config.Trade.Doctor.Items = {
	{
		["ItemClass"] = "med_health_vial",
		["ItemModel"] = "models/healthvial.mdl",
		["ItemName"] = "Флакон биогеля",
		["ItemDescription"] = "Восстанавливает 15 единиц здоровья",
		["ItemCost"] = 25,
		["ItemCategory"] = "Первая помощь",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_health_kit",
		["ItemModel"] = "models/items/healthkit.mdl",
		["ItemName"] = "Аптечка",
		["ItemDescription"] = "Восстанавливает 45 единиц здоровья",
		["ItemCost"] = 75,
		["ItemCategory"] = "Первая помощь",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_tire",
		["ItemModel"] = "models/gibs/metal_gib2.mdl",
		["ItemName"] = "Шина",
		["ItemDescription"] = "Восстанавливает переломы костей",
		["ItemCost"] = 135,
		["ItemCategory"] = "Первая помощь",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/Items/HealthKit.mdl",
		["ItemName"] = "Медицинский сканер",
		["ItemDescription"] = "Необходимый инструмент любого врача",
		["ItemCost"] = 500,
		["WeaponClass"] = "weapon_medical_scanner",
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_amitriptyline",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Амитриптилин",
		["ItemDescription"] = "Показания: депрессия и другие расстройства психики",
		["ItemCost"] = 52,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_cardionix_z2",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Кардионикс Z-2",
		["ItemDescription"] = "Показания: сердечная недостаточность",
		["ItemCost"] = 74,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_combicillin",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Комбициллин",
		["ItemDescription"] = "Показания: пневмония, острый гломерулонефрит",
		["ItemCost"] = 38,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_heptender",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Гептендер",
		["ItemDescription"] = "Показания: вирусные гепатиты, цирроз",
		["ItemCost"] = 25,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_hrzs",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Схема ГРЗС",
		["ItemDescription"] = "Показания: туберкулез",
		["ItemCost"] = 44,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_i306n",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "I306N",
		["ItemDescription"] = "Показания: СПИД",
		["ItemCost"] = 107,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.LEGENDARY,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_pulmonifer",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Пульмонифер",
		["ItemDescription"] = "Показания: хроническая обструктивная болезнь легких",
		["ItemCost"] = 94,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_qurantimycin",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Кварантимицин",
		["ItemDescription"] = "Показания: эндокардит",
		["ItemCost"] = 24,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_zenocillin",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Зеноциллин",
		["ItemDescription"] = "Показания: гнойный менингит",
		["ItemCost"] = 78,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false,
	},
}

RISED.Config.Trade.Clothes = {}
RISED.Config.Trade.Clothes.Refrash = 1200
RISED.Config.Trade.Clothes.IsRandomRotation = false
RISED.Config.Trade.Clothes.MaxItems = 5
RISED.Config.Trade.Clothes.Items = {
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/props_junk/cardboard_box004a.mdl",
		["ItemName"] = "Респиратор",
		["ItemCost"] = 2500,
		["ClothSkin"] = 0,
		["ClothType"] = "Mask",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,2,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/props_junk/cardboard_box004a.mdl",
		["ItemName"] = "Строительная маска",
		["ItemCost"] = 500,
		["ClothSkin"] = 0,
		["ClothType"] = "Mask",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,1,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/facewrap.mdl",
		["ItemName"] = "Маска",
		["ItemCost"] = 1230,
		["ClothSkin"] = 0,
		["ClothType"] = "Mask",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,4,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/wintercoat.mdl",
		["ItemName"] = "Темно-бирюзовая куртка",
		["ItemCost"] = 2700,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {16,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/wintercoat.mdl",
		["ItemName"] = "Темно-красная куртка",
		["ItemCost"] = 2400,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {17,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/wintercoat.mdl",
		["ItemName"] = "Бело-синяя куртка",
		["ItemCost"] = 1700,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {15,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/wintercoat.mdl",
		["ItemName"] = "Зеленая кофта",
		["ItemCost"] = 1200,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {14,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/props_junk/cardboard_box004a.mdl",
		["ItemName"] = "Темная кепка",
		["ItemCost"] = 2000,
		["ClothSkin"] = 0,
		["ClothType"] = "Head",
		["PlayerBodygroups"] = {0,0,0,5,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/props_junk/cardboard_box004a.mdl",
		["ItemName"] = "Синяя кепка",
		["ItemCost"] = 350,
		["ClothSkin"] = 0,
		["ClothType"] = "Head",
		["PlayerBodygroups"] = {0,0,0,7,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/beanie_green.mdl",
		["ItemName"] = "ID пропуск",
		["ItemCost"] = 450,
		["ClothSkin"] = 0,
		["ClothType"] = "ID",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,1,0,0,0,0,0},
		["Blocked"] = true,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/beanie_green.mdl",
		["ItemName"] = "Зеленая шапка",
		["ItemCost"] = 640,
		["ClothSkin"] = 0,
		["ClothType"] = "Head",
		["PlayerBodygroups"] = {0,0,0,2,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/beanie_blue.mdl",
		["ItemName"] = "Синяя шапка",
		["ItemCost"] = 700,
		["ClothSkin"] = 0,
		["ClothType"] = "Head",
		["PlayerBodygroups"] = {0,0,0,4,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/aphelion/beanie.mdl",
		["ItemName"] = "Серая шапка",
		["ItemCost"] = 800,
		["ClothSkin"] = 1,
		["ClothType"] = "Head",
		["PlayerBodygroups"] = {0,0,0,1,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/aphelion/beanie.mdl",
		["ItemName"] = "Черная шапка",
		["ItemCost"] = 400,
		["ClothSkin"] = 0,
		["ClothType"] = "Head",
		["PlayerBodygroups"] = {0,0,0,3,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/1_glasses.mdl",
		["ItemName"] = "Очки",
		["ItemCost"] = 750,
		["ClothSkin"] = 0,
		["ClothType"] = "Glasses",
		["PlayerBodygroups"] = {0,0,0,0,0,1,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/gloves_finger.mdl",
		["ItemName"] = "Открытые перчатки",
		["ItemCost"] = 550,
		["ClothSkin"] = 0,
		["ClothType"] = "Hands",
		["PlayerBodygroups"] = {0,0,1,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/gloves_full.mdl",
		["ItemName"] = "Закрытые перчатки",
		["ItemCost"] = 450,
		["ClothSkin"] = 0,
		["ClothType"] = "Hands",
		["PlayerBodygroups"] = {0,0,2,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_green.mdl",
		["ItemName"] = "Зеленая рубашка",
		["ItemCost"] = 900,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {5,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_labcoat.mdl",
		["ItemName"] = "Лабораторный халат",
		["ItemCost"] = 1100,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {22,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = true,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_loyal.mdl",
		["ItemName"] = "Рубашка лоялиста",
		["ItemCost"] = 4500,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {21,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_medic.mdl",
		["ItemName"] = "Голубая рубашка",
		["ItemCost"] = 870,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {7,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_refuge.mdl",
		["ItemName"] = "Белая рубашка",
		["ItemCost"] = 1470,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {4,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_suit_black.mdl",
		["ItemName"] = "Классический черный пиджак",
		["ItemCost"] = 7000,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {38,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/top_suit_brown.mdl",
		["ItemName"] = "Классический коричневый пиджак",
		["ItemCost"] = 8000,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {40,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/pants_black.mdl",
		["ItemName"] = "Черные джинсы",
		["ItemCost"] = 2200,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,10,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/pants_loyal.mdl",
		["ItemName"] = "Штаны лоялиста",
		["ItemCost"] = 4500,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,7,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/pants_sci.mdl",
		["ItemName"] = "Зеленые штаны в желтую полоску",
		["ItemCost"] = 1500,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,2,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/pants_yellow.mdl",
		["ItemName"] = "Желтые джинсы",
		["ItemCost"] = 1700,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,11,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/pants_suit_black.mdl",
		["ItemName"] = "Черные классические брюки",
		["ItemCost"] = 3500,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,16,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/rrp/citizen/clothing_items/pants_suit_brown.mdl",
		["ItemName"] = "Коричневые классические брюки",
		["ItemCost"] = 4000,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,17,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/aphelion/shirt_citizen1.mdl",
		["ItemName"] = "Униформа ГСР",
		["ItemCost"] = 400,
		["ClothSkin"] = 2,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {1,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = true,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/aphelion/shirt_citizen1.mdl",
		["ItemName"] = "Синяя рубашка с логотипом",
		["ItemCost"] = 700,
		["ClothSkin"] = 1,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {10,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/aphelion/shirt_citizen1.mdl",
		["ItemName"] = "Закрытая темная куртка",
		["ItemCost"] = 1400,
		["ClothSkin"] = 3,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {8,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/aphelion/shirt_citizen2.mdl",
		["ItemName"] = "Открытая темная куртка",
		["ItemCost"] = 1250,
		["ClothSkin"] = 3,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {9,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/bag.mdl",
		["ItemName"] = "Рюкзак",
		["ItemCost"] = 3250,
		["ClothSkin"] = 1,
		["ClothType"] = "Bag back",
		["PlayerBodygroups"] = {0,0,0,0,1,0,0,0,0,0,0,0,0,0},
		["Blocked"] = true,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/shirt_metrocop.mdl",
		["ItemName"] = "Вверх призывника",
		["ItemCost"] = 9000,
		["ClothSkin"] = 0,
		["ClothType"] = "Torso",
		["PlayerBodygroups"] = {25,0,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = true,
	},
	{
		["ItemClass"] = "rised_cloth",
		["ItemModel"] = "models/tnb/items/pants_metrocop.mdl",
		["ItemName"] = "Низ призывника",
		["ItemCost"] = 8500,
		["ClothSkin"] = 0,
		["ClothType"] = "Legs",
		["PlayerBodygroups"] = {0,9,0,0,0,0,0,0,0,0,0,0,0,0},
		["Blocked"] = true,
	},

}

RISED.Config.Trade.GunDealer = {}
RISED.Config.Trade.GunDealer.Refrash = 1200
RISED.Config.Trade.GunDealer.MaxItems = 12
RISED.Config.Trade.GunDealer.Items = {
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_sawedoff.mdl",
		["ItemName"] = "Обрез",
		["ItemCost"] = 12000,
		["WeaponClass"] = "swb_sawedoff",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_nam_tokarev.mdl",
		["ItemName"] = "Пистолет Токарева",
		["ItemCost"] = 7500,
		["WeaponClass"] = "swb_tt",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_toz_194m.mdl",
		["ItemName"] = "ТОЗ",
		["ItemCost"] = 17000,
		["WeaponClass"] = "swb_toz",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/insurgency/w_sks.mdl",
		["ItemName"] = "СКС",
		["ItemCost"] = 23000,
		["WeaponClass"] = "swb_sks",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_rpk_74m.mdl",
		["ItemName"] = "РПК",
		["ItemCost"] = 20000,
		["WeaponClass"] = "swb_rpk",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_gsh18.mdl",
		["ItemName"] = "ГШ-18",
		["ItemCost"] = 8000,
		["WeaponClass"] = "swb_gsh18",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/tfa_ins2/w_mosin.mdl",
		["ItemName"] = "Винтовка Мосина",
		["ItemCost"] = 22000,
		["WeaponClass"] = "swb_mosin",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/tfa_ins2/w_asval.mdl",
		["ItemName"] = "АС Вал",
		["ItemCost"] = 27000,
		["WeaponClass"] = "swb_asval",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.LEGENDARY,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/insurgency/w_ak74.mdl",
		["ItemName"] = "АК-74",
		["ItemCost"] = 25500,
		["WeaponClass"] = "swb_ak74",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_inss2_mp5a5.mdl",
		["ItemName"] = "MP5A5",
		["ItemCost"] = 17000,
		["WeaponClass"] = "swb_mp5a5",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_9x19",
		["ItemModel"] = "models/items/9x19.mdl",
		["ItemName"] = "Патроны 9x19mm",
		["ItemCost"] = 700,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_9x39",
		["ItemModel"] = "models/items/9x39.mdl",
		["ItemName"] = "Патроны 9x39мм",
		["ItemCost"] = 300,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_12x70",
		["ItemModel"] = "models/items/12x70.mdl",
		["ItemName"] = "Патроны 12x70мм",
		["ItemCost"] = 500,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_545x39",
		["ItemModel"] = "models/items/545x39.mdl",
		["ItemName"] = "Патроны 5,45x39мм",
		["ItemCost"] = 550,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_762x25",
		["ItemModel"] = "models/items/762x25.mdl",
		["ItemName"] = "Патроны 7,62x25мм",
		["ItemCost"] = 800,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_762x39",
		["ItemModel"] = "models/items/762x39.mdl",
		["ItemName"] = "Патроны 7,62x39мм",
		["ItemCost"] = 800,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "ammo_762x54r",
		["ItemModel"] = "models/Items/boxsniperroundz.mdl",
		["ItemName"] = "Патроны 7,62x54Rмм",
		["ItemCost"] = 800,
		["ItemCategory"] = "Патроны",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.LEGENDARY,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rised_cloth_armor_class2",
		["ItemModel"] = "models/tnb/items/aphelion/shirt_rebelmetrocop.mdl",
		["ItemName"] = "Бронежилет II класса",
		["ItemCost"] = 10000,
		["ItemCategory"] = "Броня",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["ClothSkin"] = 0,
		["ClothType"] = "Armor",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,0,1,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth_armor_class3",
		["ItemModel"] = "models/rrp/citizen/clothing_items/rebel_top_green.mdl",
		["ItemName"] = "Бронежилет III класса",
		["ItemCost"] = 16000,
		["ItemCategory"] = "Броня",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["ClothSkin"] = 0,
		["ClothType"] = "Armor",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,0,3,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth_armor_class3_medic",
		["ItemModel"] = "models/rrp/citizen/clothing_items/rebel_med_top_blue.mdl",
		["ItemName"] = "Бронежилет медика III класса",
		["ItemCost"] = 15000,
		["ItemCategory"] = "Броня",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["ClothSkin"] = 0,
		["ClothType"] = "Armor",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,0,2,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth_armor_class4",
		["ItemModel"] = "models/tnb/items/shirt_rebel_molle.mdl",
		["ItemName"] = "Бронежилет IV класса",
		["ItemCost"] = 20000,
		["ItemCategory"] = "Броня",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["ClothSkin"] = 0,
		["ClothType"] = "Armor",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,0,4,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "rised_cloth_armor_class5_combine",
		["ItemModel"] = "models/tnb/items/aphelion/shirt_rebeloverwatch.mdl",
		["ItemName"] = "Бронежилет Солдата Надзора",
		["ItemCost"] = 26000,
		["ItemCategory"] = "Броня",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.LEGENDARY,
		["ClothSkin"] = 0,
		["ClothType"] = "Armor",
		["PlayerBodygroups"] = {0,0,0,0,0,0,0,0,0,0,5,0,0,0},
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_emptool.mdl",
		["ItemName"] = "Взломщик полей Альянса",
		["ItemCost"] = 3500,
		["WeaponClass"] = "weapon_combinedoor_hacker",
		["ItemCategory"] = "Инструменты",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.LEGENDARY,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rised_flashlight",
		["ItemModel"] = "models/flashns/w_knife_t.mdl",
		["ItemName"] = "Фонарик",
		["ItemCost"] = 700,
		["ItemCategory"] = "Инструменты",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
}

RISED.Config.Trade.Outland = {}
RISED.Config.Trade.Outland.Refrash = 1200
RISED.Config.Trade.Outland.MaxItems = 5
RISED.Config.Trade.Outland.Items = {
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_nam_tokarev.mdl",
		["ItemName"] = "Пистолет Токарева",
		["ItemCost"] = 7500,
		["WeaponClass"] = "swb_tt",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "spawned_weapon",
		["ItemModel"] = "models/weapons/w_gsh18.mdl",
		["ItemName"] = "ГШ-18",
		["ItemCost"] = 8000,
		["WeaponClass"] = "swb_gsh18",
		["ItemCategory"] = "Оружие",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rised_flashlight",
		["ItemModel"] = "models/flashns/w_knife_t.mdl",
		["ItemName"] = "Фонарик",
		["ItemCost"] = 500,
		["ItemCategory"] = "Инструменты",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rcs_ing_ammo_sleeve",
		["ItemModel"] = "models/props_lab/reciever01d.mdl",
		["ItemName"] = "Гильзы",
		["ItemCost"] = 200,
		["ItemCategory"] = "Запчасти",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rcs_ing_ammo_bullet",
		["ItemModel"] = "models/props_lab/reciever01d.mdl",
		["ItemName"] = "Пули",
		["ItemCost"] = 300,
		["ItemCategory"] = "Запчасти",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rcs_ing_wep_spring",
		["ItemModel"] = "models/props_lab/reciever01d.mdl",
		["ItemName"] = "Пружина",
		["ItemCost"] = 500,
		["ItemCategory"] = "Запчасти",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "rcs_ing_wep_gas_tube",
		["ItemModel"] = "models/props_lab/reciever01d.mdl",
		["ItemName"] = "Газовая трубка",
		["ItemCost"] = 450,
		["ItemCategory"] = "Запчасти",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.RARE,
		["Blocked"] = false
	},
	{
		["ItemClass"] = "med_health_vial",
		["ItemModel"] = "models/healthvial.mdl",
		["ItemName"] = "Флакон биогеля",
		["ItemCost"] = 500,
		["ItemCategory"] = "Первая помощь",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.UNCOMMON,
		["Blocked"] = false,
	},
	{
		["ItemClass"] = "med_drug_amitriptyline",
		["ItemModel"] = "models/props_lab/jar01b.mdl",
		["ItemName"] = "Амитриптилин",
		["ItemCost"] = 2000,
		["ItemCategory"] = "Терапия",
		["ItemChance"] = RISED.Config.Trade.ItemsRarity.COMMON,
		["Blocked"] = false,
	},
}

RISED.Config.Trade.Furniture = {}
RISED.Config.Trade.Furniture.Refrash = 1200
RISED.Config.Trade.Furniture.IsRandomRotation = false
RISED.Config.Trade.Furniture.MaxItems = 5
RISED.Config.Trade.Furniture.Items = {
	{
		["ItemModel"] = "models/props_c17/chair02a.mdl",
		["ItemName"] = "Металлический стул",
		["ItemCost"] = 100,
		["Blocked"] = false,
	},
	{
		["ItemModel"] = "models/props_c17/FurnitureCouch001a.mdl",
		["ItemName"] = "Диван",
		["ItemCost"] = 125,
		["Blocked"] = false,
	},
	{
		["ItemModel"] = "models/props_interiors/BathTub01a.mdl",
		["ItemName"] = "Ванна",
		["ItemCost"] = 200,
		["Blocked"] = false,
	},
}

RISED.Config.Trade.Contraband = {}
RISED.Config.Trade.Contraband.Refrash = 1200
RISED.Config.Trade.Contraband.Items = {
	[1] = {
		["ItemClass"] = "rised_flashlight",
		["ItemName"] = "Фонарик",
		["ItemCost"] = 500,
		["Blocked"] = false,
	},
	[2] = {
		["ItemClass"] = "watch",
		["ItemName"] = "Часы",
		["ItemCost"] = 700,
		["Blocked"] = false,
	},
	[3] = {
		["ItemClass"] = "ammo_9x19",
		["ItemName"] = "Патроны 9x19мм",
		["ItemCost"] = 700,
		["Blocked"] = false,
	},
	[4] = {
		["ItemClass"] = "ammo_9x39",
		["ItemName"] = "Патроны 9x39мм",
		["ItemCost"] = 800,
		["Blocked"] = false,
	},
	[5] = {
		["ItemClass"] = "ammo_12x70",
		["ItemName"] = "Патроны 12x70мм",
		["ItemCost"] = 500,
		["Blocked"] = false,
	},
	[6] = {
		["ItemClass"] = "ammo_545x39",
		["ItemName"] = "Патроны 5,45x39мм",
		["ItemCost"] = 800,
		["Blocked"] = false,
	},
	[7] = {
		["ItemClass"] = "ammo_762x25",
		["ItemName"] = "Патроны 7,62x25мм",
		["ItemCost"] = 800,
		["Blocked"] = false,
	},
	[8] = {
		["ItemClass"] = "ammo_762x39",
		["ItemName"] = "Патроны 7,62x39мм",
		["ItemCost"] = 800,
		["Blocked"] = false,
	},
	[9] = {
		["ItemClass"] = "ammo_762x54r",
		["ItemName"] = "Патроны 7,62x54Rмм",
		["ItemCost"] = 700,
		["Blocked"] = false,
	},
	[10] = {
		["ItemClass"] = "cuw_rationpoison",
		["ItemName"] = "Яд",
		["ItemCost"] = 500,
		["Blocked"] = false,
	},
	[11] = {
		["ItemClass"] = "watch",
		["ItemName"] = "Часы",
		["ItemCost"] = 700,
		["Blocked"] = false,
	},
	[12] = {
		["ItemClass"] = "rhc_lockpick",
		["ItemName"] = "Отмычка для наручников",
		["ItemCost"] = 1000,
		["Blocked"] = false,
	},
	
	[13] = {
		["ItemClass"] = "rcs_ing_wep_barrel5x45",
		["ItemName"] = "Ствол 5.45мм",
		["ItemCost"] = 600,
		["Blocked"] = true,
	},
	[14] = {
		["ItemClass"] = "rcs_ing_wep_barrel7x62",
		["ItemName"] = "Ствол 7.62мм",
		["ItemCost"] = 800,
		["Blocked"] = true,
	},
	[15] = {
		["ItemClass"] = "rcs_ing_wep_barrel9x19",
		["ItemName"] = "Ствол 9.19мм",
		["ItemCost"] = 300,
		["Blocked"] = true,
	},
	[16] = {
		["ItemClass"] = "rcs_ing_wep_barrel9x39",
		["ItemName"] = "Ствол 9.39мм",
		["ItemCost"] = 400,
		["Blocked"] = true,
	},
	[17] = {
		["ItemClass"] = "rcs_ing_wep_barrel10x33",
		["ItemName"] = "Ствол 10.33мм",
		["ItemCost"] = 800,
		["Blocked"] = true,
	},
	[18] = {
		["ItemClass"] = "rcs_ing_wep_barrel18x5",
		["ItemName"] = "Ствол 18.5мм",
		["ItemCost"] = 800,
		["Blocked"] = true,
	},
	[19] = {
		["ItemClass"] = "rcs_ing_wep_block_trigger",
		["ItemName"] = "Колодка от курковки",
		["ItemCost"] = 700,
		["Blocked"] = true,
	},
	[29] = {
		["ItemClass"] = "rcs_ing_wep_forend_pst",
		["ItemName"] = "Цевье продольно-скользящего типа",
		["ItemCost"] = 730,
		["Blocked"] = true,
	},
	[30] = {
		["ItemClass"] = "rcs_ing_wep_gas_cutoff_reflector",
		["ItemName"] = "Отсечка-отражатель",
		["ItemCost"] = 500,
		["Blocked"] = true,
	},
	[31] = {
		["ItemClass"] = "rcs_ing_wep_gas_tube",
		["ItemName"] = "Газовая трубка",
		["ItemCost"] = 600,
		["Blocked"] = true,
	},
	[32] = {
		["ItemClass"] = "rcs_ing_wep_shutter_bt",
		["ItemName"] = "Затвор болтового типа",
		["ItemCost"] = 800,
		["Blocked"] = true,
	},
	[33] = {
		["ItemClass"] = "rcs_ing_wep_shutter_ejector_trigger",
		["ItemName"] = "Эжектор от курковки",
		["ItemCost"] = 500,
		["Blocked"] = true,
	},
	[34] = {
		["ItemClass"] = "rcs_ing_wep_shutter_pst",
		["ItemName"] = "Продольно-скользящий затвор",
		["ItemCost"] = 450,
		["Blocked"] = true,
	},
	[35] = {
		["ItemClass"] = "rcs_ing_wep_shutter_rt",
		["ItemName"] = "Затвор рычажного типа",
		["ItemCost"] = 400,
		["Blocked"] = true,
	},
	[36] = {
		["ItemClass"] = "rcs_ing_wep_spring",
		["ItemName"] = "Возвратная пружина",
		["ItemCost"] = 400,
		["Blocked"] = true,
	},
	[37] = {
		["ItemClass"] = "rcs_ing_wep_usm_c",
		["ItemName"] = "УСМ куркового типа",
		["ItemCost"] = 400,
		["Blocked"] = true,
	},
	[38] = {
		["ItemClass"] = "rcs_ing_wep_usm_x1",
		["ItemName"] = "Однорежимный УСМ",
		["ItemCost"] = 300,
		["Blocked"] = true,
	},
	[39] = {
		["ItemClass"] = "rcs_ing_wep_usm_x2",
		["ItemName"] = "Двухрежимный УСМ",
		["ItemCost"] = 500,
		["Blocked"] = true,
	},
	[40] = {
		["ItemClass"] = "schema_357",
		["ItemName"] = "Чертеж CZ-75",
		["ItemCost"] = 4000,
		["Blocked"] = true,
	},
	[41] = {
		["ItemClass"] = "schema_ak74",
		["ItemName"] = "Чертеж АК-74",
		["ItemCost"] = 6000,
		["Blocked"] = true,
	},
	[42] = {
		["ItemClass"] = "schema_akm",
		["ItemName"] = "Чертеж АКМ",
		["ItemCost"] = 6000,
		["Blocked"] = true,
	},
	[43] = {
		["ItemClass"] = "schema_asval",
		["ItemName"] = "Чертеж АС 'Вал'",
		["ItemCost"] = 5000,
		["Blocked"] = true,
	},
	[44] = {
		["ItemClass"] = "schema_cheytac",
		["ItemName"] = "Чертеж CheyTac M200",
		["ItemCost"] = 10000,
		["Blocked"] = true,
	},
	[45] = {
		["ItemClass"] = "schema_gsh18",
		["ItemName"] = "Чертеж ГШ-18",
		["ItemCost"] = 2500,
		["Blocked"] = true,
	},
	[46] = {
		["ItemClass"] = "schema_hammer",
		["ItemName"] = "Чертеж HAMMER",
		["ItemCost"] = 20000,
		["Blocked"] = true,
	},
	[47] = {
		["ItemClass"] = "schema_irifle",
		["ItemName"] = "Чертеж iRifle",
		["ItemCost"] = 2500,
		["Blocked"] = true,
	},
	[48] = {
		["ItemClass"] = "schema_ismg",
		["ItemName"] = "Чертеж iSMG",
		["ItemCost"] = 2000,
		["Blocked"] = true,
	},
	[49] = {
		["ItemClass"] = "schema_lmg",
		["ItemName"] = "Чертеж LMG",
		["ItemCost"] = 800,
		["Blocked"] = true,
	},
	[50] = {
		["ItemClass"] = "schema_mosin",
		["ItemName"] = "Чертеж винтовки Мосина",
		["ItemCost"] = 1100,
		["Blocked"] = true,
	},
	[51] = {
		["ItemClass"] = "schema_pistol",
		["ItemName"] = "Чертеж USP Match",
		["ItemCost"] = 400,
		["Blocked"] = true,
	},
	[52] = {
		["ItemClass"] = "schema_rpk",
		["ItemName"] = "Чертеж РПК",
		["ItemCost"] = 650,
		["Blocked"] = true,
	},
	[53] = {
		["ItemClass"] = "schema_sawedoff",
		["ItemName"] = "Чертеж Обреза",
		["ItemCost"] = 300,
		["Blocked"] = true,
	},
	[54] = {
		["ItemClass"] = "schema_shotgun",
		["ItemName"] = "Чертеж SPAS-12",
		["ItemCost"] = 500,
		["Blocked"] = true,
	},
	[55] = {
		["ItemClass"] = "schema_sks",
		["ItemName"] = "Чертеж СКС",
		["ItemCost"] = 800,
		["Blocked"] = true,
	},
	[56] = {
		["ItemClass"] = "schema_smg",
		["ItemName"] = "Чертеж MP7",
		["ItemCost"] = 450,
		["Blocked"] = true,
	},
	[57] = {
		["ItemClass"] = "schema_toz",
		["ItemName"] = "Чертеж ТОЗ",
		["ItemCost"] = 450,
		["Blocked"] = true,
	},
	[58] = {
		["ItemClass"] = "schema_tt",
		["ItemName"] = "Чертеж пистолета Токарева",
		["ItemCost"] = 100,
		["Blocked"] = true,
	},


	---=== WEAPONS ===---
	[13] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Рация",
		["ItemCost"] = 100,
		["WeaponClass"] = "wep_jack_job_drpradio",
		["Blocked"] = false,
	},
	[14] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Combine Door Hacker",
		["ItemCost"] = 5000,
		["WeaponClass"] = "weapon_combinedoor_hacker",
		["Blocked"] = false,
	},
	[15] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Beta-декриптор N-7",
		["ItemCost"] = 2500,
		["WeaponClass"] = "weapon_decryptor",
		["Blocked"] = false,
	},
	[16] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Самодельные наручники",
		["ItemCost"] = 1500,
		["WeaponClass"] = "weapon_cuff_rope",
		["Blocked"] = false,
	},
	[17] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Гитара",
		["ItemCost"] = 500,
		["WeaponClass"] = "guitar_stalker",
		["Blocked"] = false,
	},
	[18] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Беламорканал",
		["ItemCost"] = 500,
		["WeaponClass"] = "weapon_ciga_cheap",
		["Blocked"] = false,
	},
	[19] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Отмычка для взлома",
		["ItemCost"] = 1000,
		["WeaponClass"] = "weapon_lockpick_shot",
		["Blocked"] = false,
	},
	[21] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Топор",
		["ItemCost"] = 400,
		["WeaponClass"] = "weapon_hl2axe",
		["Blocked"] = false,
	},
	[59] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "USP Match",
		["ItemCost"] = 3000,
		["WeaponClass"] = "swb_pistol",
		["Blocked"] = false,
	},
	[60] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "ГШ-18",
		["ItemCost"] = 2890,
		["WeaponClass"] = "swb_gsh18",
		["Blocked"] = false,
	},
	[61] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Обрез",
		["ItemCost"] = 5000,
		["WeaponClass"] = "swb_sawedoff",
		["Blocked"] = false,
	},
	[62] = {
		["ItemClass"] = "spawned_weapon",
		["ItemName"] = "Пистолет Токарева",
		["ItemCost"] = 1500,
		["WeaponClass"] = "swb_tt",
		["Blocked"] = false,
	},
}